---
- hosts: ubuntu
  become: true
  tasks:
    - name: Install cowsay
      ansible.builtin.apt:
        name: cowsay
        update_cache: true
        state: latest

    - name: Run cowsay command
      ansible.builtin.command: /usr/games/cowsay "hello {{ ansible_nodename }}"
      register: cs

    - name: Debug output of cowsay
      ansible.builtin.debug:
        var: cs
