---
- name: Gather debug info for Debian hosts
  hosts: astra
  become: false

  tasks:
    - name: Ensure sysstat and procps are installed (Debian/Ubuntu)
      ansible.builtin.apt:
        name:
          - sysstat
          - procps
        state: present
      when: ansible_os_family == "Debian"

    - name: Gather recent vmstat info
      ansible.builtin.command: /usr/bin/vmstat 1 5
      register: vmstat

    - name: Gather top CPU hogs
      ansible.builtin.command: /usr/bin/ps -eo user:20,pid,size,pcpu,cmd --sort=-pcpu
      register: pscpu

    - name: Gather top memory hogs
      ansible.builtin.command: /usr/bin/ps -eo user:20,pid,size,pcpu,cmd --sort=-size
      register: pssize

    - name: Swap + wait states
      ansible.builtin.debug:
        var: vmstat.stdout_lines

    - name: Top 5 CPU hogs
      ansible.builtin.debug:
        var: pscpu.stdout_lines[:6]

    - name: Top 5 memory hogs
      ansible.builtin.debug:
        var: pssize.stdout_lines[:6]
