---
- name: Install and configurate Nginx
  hosts: all
  vars:
    nginx_port: 8081
    root_dir: /usr/share/nginx/html
    message: "This is server {{ ansible_nodename }}!"

  become: true
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
    - name: update nginx config
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
    - name: update nginx config
      ansible.builtin.template:
        src: files/index.html.j2
        dest: "{{ root_dir }}/index.html"
      notify:
        - restart nginx
